### PR TITLE
modifying wait times

### PR DESCRIPTION
**Pull request by rpauly18**
Trying to fix the 429 errors

### CODE REVIEW

**Comment by ssolson** [comment]
What is it that they changed that made this a problem recently? I mean it had been working for months right?

**Comment by rpauly18** [comment]
I do not think anything changed. We did not have many PRs after we merged the hindcast function. We probably just got lucky during the review process of the hindcast function. Other errors that were thrown during the process likely masked or prevented 429 from ever being thrown. I would say currently ~25% of the time our tests pass without this error being thrown

**Comment by rpauly18** [comment]
My preference at the moment would be to reconfigure the tests so that the hindcast tests are only run with one version of Python. This will take some reworking of the travis.yml file. We could also reconfigure the tests so that the hindcast functions are only run under certain circumstances- but that route is little less straight forward to me.

**Comment by ssolson** [comment]
> I do not think anything changed. We did not have many PRs after we merged the hindcast function. We probably just got lucky during the review process of the hindcast function. Other errors that were thrown during the process likely masked or prevented 429 from ever being thrown. I would say currently ~25% of the time our tests pass without this error being thrown

As far as I can tell every build has failed since you added the new hsds keys commit. I do no think we were lucky before. Am I missing a commit that has passed following the hsds commit?

**Comment by rpauly18** [comment]
Yes, some commits have passed. What I was doing was restarting the build after they passed to see if the changes that were made truly fixed the issue or if it was a case of us just getting lucky. Every time it would fail when I restarted the build.

**Comment by ssolson** [comment]
I do not think we were "lucky" before though. Can we agree that no build ever failed prior to the new hsds commit? It appears to me that there were sufficient commits in this time to see at least 1 build fail.

Can you explain to me what is going on with the commit I just made?

How did I pass Travis but fail coveralls? When I look at the details it is not clear to me how I am failing this.

**Comment by rpauly18** [comment]
I am not really sure. The coveralls check started appearing recently- I do not recall seeing that check in the past. I am guessing because the coverage decreased?

**Comment by ssolson** [comment]
Yep that seems to be the issue. I have modified the coveralls.io settings and I am checking if the build will pass now. 

https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-120924694

**Comment by ssolson** [comment]
So as a note sleeping between 2 and 10 minutes randomly seems to avoid the issue. I am not going to run the tests using an if statement to only run the hindcast test for Python 3.8.

**Comment by ssolson** [comment]
Interesting. So this worked on the build side but drops our total coverage below 90% because we are no longer testing in 3.7 and 3.9 how frustrating. Okay I will try to do one test in each version,

**Comment by ssolson** [comment]
@rpauly18 I think we are good here. Let's get this merged into the main ASAP.

**Review by ssolson — APPROVED** [review]

**Pull request merged**
