### PR TITLE
Handle RDI's variable profile shenanigans

### PR DESCRIPTION
**Pull request by jmcvey3**
Introduces fixes for RDI files that contain changing "number of cells" and variable "cell sizes". The latter are bin-averaged into the largest cell size. Issue #291

### CODE REVIEW

**Comment by jmcvey3** [comment]
@browniea When you get a chance, see if this works for you. The range may still offset based on whatever the "bin1_dist_m" attribute, but that should be easily adjusted.

**Comment by browniea** [comment]
@jmcvey3  Looks like there is a conflict with the latest merge [#286](https://github.com/MHKiT-Software/MHKiT-Python/issues/286)

**Comment by jmcvey3** [comment]
> @jmcvey3 Looks like there is a conflict with the latest merge [#286](https://github.com/MHKiT-Software/MHKiT-Python/issues/286)

Yeah that's annoying

**Comment by browniea** [comment]
The variable bin size is still being missed but the number of bins is right! 
image

**Comment by jmcvey3** [comment]
> The variable bin size is still being missed but the number of bins is right! image

Sweet. The data from the 0.12 m bins is stored in the variables with an "_sl" tag, so I'm sure it wouldn't be difficult to write a function to combine these two. However, I don't think that function would belong in the reader, since the goal of the reader is to read what's in the datafile and do no more processing than necessary.

**Comment by browniea** [comment]
That makes sense and I agree.  I can include that in my next example notebook for UMERC stuff.

**Review by browniea — APPROVED** [review]

**Comment by jmcvey3** [comment]
> That makes sense and I agree. I can include that in my next example notebook for UMERC stuff.

Great, yes I think that's a good idea, especially since TRDI is retiring the Workhorse line and pushing these newer instruments.

**Pull request merged**
