### PR TITLE
Automatic optimal threshold for peaks-over-threshold method

### PR DESCRIPTION
**Pull request by cmichelenstrofer**
Automatic threshold for peaks-over-threshold developed by Vince Neary and Seongho Ahn.

### CODE REVIEW

**Comment by cmichelenstrofer** [comment]
FYI @Graham-EGI @mbruggs

**Comment by cmichelenstrofer** [comment]
@akeeste @ssolson we already have a peaks-over-threshold method, which takes in `threshold` as one of the inputs. This method here is to automatically calculate the "best" threshold. It is from a paper by Vince and Seongho: 

Neary, V. S., S. Ahn, B. E. Seng, M. N. Allahdadi, T. Wang, Z. Yang and R. He (2020). "Characterization of Extreme Wave Conditions for Wave Energy Converter Design and Project Risk Assessment.” J. Mar. Sci. Eng. 2020, 8(4), 289; https://doi.org/10.3390/jmse8040289.

They had it in Matlab and I converted it to Python here.

**Comment by ssolson** [comment]
Hey @cmichelenstrofer I wanted to check in on if you had any offline progress on this PR?

**Comment by cmichelenstrofer** [comment]
@ssolson No, I really need to to get back to it and wrap it up. I'll try to find some time to do that in the next couple of weeks.

**Comment by ssolson** [comment]
Hey @cmichelenstrofer I wanted to check in on this PR.

I was going to try to sum up your changes and look at taking it over or closing it due to inactivity but the diff in on 137 files and I'm not sure exactly what you changed (without more effort than simply asking).

How close is the work that have done to completion and could you point out exactly what you added?

**Comment by cmichelenstrofer** [comment]
This branch got messed up real bad. will open an new PR.

**Pull request closed without merging**
