### PR TITLE
concatenate multi param dfs on same index

### PR DESCRIPTION
**Pull request by ssolson**
I believe this should fix the issue I bring up in #102. So long as all the test still pass (which they did locally) we should be good to go.

### CODE REVIEW

**Comment by ssolson** [comment]
It appears that the only 1 version of python per test did not fix the "too many requests" issue. 

Okay so to keep coverage up and test the remote we can run all tests remotely for 1 version of python and add datasets to compare against locally for any other versions we test. I will add those changes here.

**Comment by ssolson** [comment]
Trying to load saved data to compare against doesn't make sense and will not solve the problem as far as I can tell. To just load data would skip running the hindcast function. If we skip running the function then we are don't testing the code and will reduce our coverage anyway.

At this point, I think that the best way to test the code maybe with a minimal call to the function run in all three versions. Remember running the tests in only one python version reduces our reported code coverage when it averages the code coverages across the tested python versions.

Before I try this I think I will add a dedicated wait to the test as they currently stand as this seems to be the best solution that I can currently think of still. Let me know if you guys have other ideas to try or if I am missing something.

**Comment by ssolson** [comment]
lol okay so the wait must be shorter than 10 minutes. One more time.

**Comment by ssolson** [comment]
oh my goodness thwarted by my own tests. Okay so it worked locally bc I run python 3.8 and the multi param is now only tests on python 3.9. This shows a confusing outcome from this hack. I really think the best outcome would be to work with the rex team to set up a wait when it receives a too many call response.

**Comment by rpauly18** [comment]
I believe the error you are getting is because of the change in the returned data from the function if you pass multiple parameters. This should be an easy fix. I can help make the modifications.

**Pull request merged**
