### PR TITLE
Adding magnitude and phase function

### PR DESCRIPTION
**Pull request by ssolson**
Simple function to calculate the magnitude and phase of floats, ints, arrays, or series in 2D or 3D added to the utils module.

@kmruehl do you think you will have time to take a look at this before your vacation?

### CODE REVIEW

**Comment by jleonqu** [comment]
Hello,

I reviewed this pull request and it worked for me. It is easy to use. I followed the instructions in this link: [​MHKiT Example](https://mhkit-software.github.io/MHKiT/wecsim_example.html) to use MHKiT with WEC-Sim data. I used the function to calculate the magnitude and phase of the data provided in the example. I run the tests and all of them passed. It was the first time I used MHKiT-Python and it was a good experience overall. It is good to have all the resources available on the webpage such as the installation guidelines and the examples, that makes the user experience a lot easier.​

**Comment by kmruehl** [comment]
@jleonqu thanks for reviewing this new feature, your feedback is much appreciated. @ssolson you can count this as my review, and from my perspective you can go ahead and merge this PR.

**Review by kmruehl — APPROVED** [review]
Refer to review from @jleonqu [here](https://github.com/MHKiT-Software/MHKiT-Python/pull/111#issuecomment-860722713)

**Comment by kmruehl** [comment]
@rpauly18 i assume the next step is to write the MATLAB wrapper? LMK when that's ready and we can start using it. Thanks!

**Review by rpauly18 — APPROVED** [review]

**Pull request merged**
