### PR TITLE
Fix warnings in the documentation build

### PR DESCRIPTION
**Pull request by akeeste**
This PR pairs with https://github.com/MHKiT-Software/MHKiT/pull/80 and aims to eliminate the volume of warnings occurring in our documentation build.

Many of these changes will probably be fixing minor spacings/lines/issues in docstrings that show up as warnings but not errors when the documentation builds. Future linting should address and prevent these issues too.

### CODE REVIEW

**Comment by akeeste** [comment]
@ssolson this should be a low lift to review when ready. We don't need to delay our release for this PR, but it would be great to merge whatever is pushed here and ready before the release. This will help me easy our documentation workflow and get that fully updated.

**Comment by ssolson** [comment]
> @ssolson this should be a low lift to review when ready. We don't need to delay our release for this PR, but it would be great to merge whatever is pushed here and ready before the release. This will help ease future documentation updates and keep it fully updated.

No it should be `typing` and in default python I pushed a fix.

**Comment by akeeste** [comment]
@ssolson I pushed a couple final commits to also resolve #355 as the pacwave notebook was resulting in an incorrect plot in the documentation.

**Review by ssolson — APPROVED** [review]
Thanks @akeeste this PR focuses on clean up of the code.

**Pull request merged**
