### PR TITLE
Introduce upcrossing analysis module

### PR DESCRIPTION
**Pull request by mbruggs**
As disussed in #230, there were no general methods for performing an upcrossing analysis. This series of commits introduces such a module and uses it to implement the existing functionality within the loads.extreme.global_peaks function.

### CODE REVIEW

**Comment by mbruggs** [comment]
Hello! Thanks as always for all the work on MHKit!

I wasn't sure exactly where to put this new functionality as it doesn't nicely sit within any of the existing modules. I opted for the `qc` module as it seems the most generic. Happy to move if you think there's somewhere better :)

**Comment by mbruggs** [comment]
It looks like the check below hasn't passed it dosen't seem to be related to my change:

Py 3.7 3.8, 3.9 | Windows Mac Linux / pip-windows-latest/3.9 (pull_request)

**Comment by ssolson** [comment]
> It looks like the check below hasn't passed it dosen't seem to be related to my change:
> 
> Py 3.7 3.8, 3.9 | Windows Mac Linux / pip-windows-latest/3.9 (pull_request)

Mark No worries and thank you. There are API issues that are being addressed in #241 .

**Comment by akeeste** [comment]
Hi @mbruggs 

Sorry for the delay. Thanks for your contribution here. I reviewed your PR and made some minor linting/docstring suggestions in https://github.com/mbruggs/MHKiT-Python/pull/2 

The last piece before merging is to find an appropriate spot for this. Right now the QC module is made up entirely of pecos functions and more focused on the clean-up of timeseries data than its analysis. 

Right now I'm leaning towards within mhkit.loads as a submodule ``mhkit.loads.upcrossing`` or within the general submodule ``mhkit.loads.general``. I'm open to discussion on location though

**Review by akeeste — CHANGES_REQUESTED** [review]
Hi @mbruggs 

Sorry for the delay. Thanks for your contribution here. I reviewed your PR and made some minor linting/docstring suggestions in https://github.com/mbruggs/MHKiT-Python/pull/2 

The last piece before merging is to find an appropriate spot for this. Right now the QC module is made up entirely of pecos functions and more focused on the clean-up of timeseries data than its analysis. 

Right now I'm leaning towards within mhkit.loads as a submodule ``mhkit.loads.upcrossing`` or within the general submodule ``mhkit.loads.general``. I'm open to discussion on location though

**Comment by mbruggs** [comment]
Thanks for the review @akeeste! I made a comment that's hopefully quick to resolve in mbruggs#2.

I agree the location of this functionality is a bit tricky. I'm more than happy for it go into `loads` - my hesitation was that the methods are equally applicable to wave analysis.

**Comment by akeeste** [comment]
@mbruggs That's a good point. Sterling and I discussed location today and decided this is probably best under ``mhkit.utils``, since it is applicable to both loads, wave data and really could be applied to any other timeseries data of interest. I'll update that in mbruggs#2 this week

**Review by akeeste — APPROVED** [review]

**Comment by mbruggs** [comment]
@akeeste Thanks very much for all your work on this!

**Pull request merged**
