### PR TITLE
Compute surface elevation using IFFT

### PR DESCRIPTION
**Pull request by mbruggs**
As discussed in #229 computing the surface elevation using the 'sum of sines' method is slow. Instead, we can use an IFFT which drastically increases performance. The IFFT method is used as the default when no frquency bins are provided and the frequency vector is equally spaced.

To compute the IFFT the zero frequency must be defined. The spectrum methods have been updated to avoid NaN values in the presence of the zero frequency. This means that spectrum and surface elevations functions work seamlessly together.

### CODE REVIEW

**Comment by ssolson** [comment]
@mbruggs you da man. 

Looking this over I think we can get this in our next release for mid-August. I promise to get you a review before then. Currently, I am reviewing several other PRs for the next release so my review of this may be a week or so out.

Thank you so much for this contribution!

**Comment by ssolson** [comment]
@akeeste could you review Mark's application of the IFFT? I am looking for help reviewing the application of the technique as I am not familiar with it.

**Comment by akeeste** [comment]
@ssolson Yes definitely. @mbruggs I'll review this PR next week

**Review by akeeste — CHANGES_REQUESTED** [review]
Hi @mbruggs 

Thanks for this great speed update. I only have a few changes to make, which I put in mbruggs/MHKiT-Python#1, including
- [x] add doc string for frequency_bins
- [x] update example notebook calls to surface_elevation to use 0 frequency and the faster IFFT method

Once that is merged, I'll go ahead and bring this into MHKiT

**Pull request merged**
