### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by ssolson**
I need CI on the main repo for this to run. Apologies everyone this creates a lot of notifications while I set this up.

### CODE REVIEW

**Comment by ssolson** [comment]
@rpauly18 we are getting an error on Python 3.7 and windows for multi_year_hindcast test. This is the second issue with python 3.7 including the previous numpy issue. Error is below. lmk if you have any idea what is going on here: 

```
test_multi_year (mhkit.tests.test_wave.TestWPTOhindcast) ... ERROR

======================================================================
ERROR: test_multi_year (mhkit.tests.test_wave.TestWPTOhindcast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\MHKiT-Python\MHKiT-Python\mhkit\tests\test_wave.py", line 961, in test_multi_year
    wave_multiyear, meta = wave.io.hindcast.request_wpto_point_data(data_type,parameters,lat_lon,years)
  File "D:\a\MHKiT-Python\MHKiT-Python\mhkit\wave\io\hindcast.py", line 131, in request_wpto_point_data
    with MultiYearWaveX(wave_path, **waveKwargs) as rex_waves:
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\rex\resource_extraction\resource_extraction.py", line 1711, in __init__
    res_cls=WaveResource)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\rex\resource_extraction\resource_extraction.py", line 1131, in __init__
    hsds=hsds, res_cls=res_cls)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\rex\multi_year_resource.py", line 504, in __init__
    years=years, res_cls=res_cls, **cls_kwargs)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\rex\multi_year_resource.py", line 46, in __init__
    years=years)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\rex\multi_year_resource.py", line 268, in _map_files
    suffix=suffix)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\rex\multi_year_resource.py", line 149, in _map_hsds_files
    with h5pyd.Folder(hsds_dir) as f:
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\h5pyd\_hl\folders.py", line 111, in __init__
    raise ValueError("Folder name must start with '/'")
ValueError: Folder name must start with '/'
-------------------- >> begin captured logging << --------------------
rex.resource_extraction.resource_extraction: INFO: Running with rex version 0.2.59
rex.resource_extraction.resource_extraction: DEBUG: - h5py version 3.3.0
rex.resource_extraction.resource_extraction: DEBUG: - numpy version 1.20.3
rex.resource_extraction.resource_extraction: DEBUG: - pandas version 1.3.0
rex.resource_extraction.resource_extraction: DEBUG: - scipy version 1.7.0
--------------------- >> end captured logging << ---------------------
```

**Comment by ssolson** [comment]
@rpauly18 with the exception of the py 3.7 windows error discussed above this PR is ready to go.

**Comment by rpauly18** [comment]
For 3.7 the only thing that looks like it has changed in terms of versions is now python 3.7.9 is being run while Travis was running 3.7.1. Not sure if that is the cause. Otherwise, nothing is immediately jumping out at me. It does bring up the question... when do we think we would want to stop supporting Python3.7?

**Comment by ssolson** [comment]
@rpauly18 I believe the issue is with the rex developers not using os specific file separators. No idea why it only breaks on the latest version of 3.7 but they fixed similar issues for us previously. The issue is here:

https://github.com/NREL/rex/blob/9a754a79ff483ddc8a17ca71dabaef4d9ba35d6f/rex/multi_year_resource.py#L146

where instead of  

```
hsds_dir.endswith('/')
```

I believe is should be 

```
hsds_dir.endswith(os.sep)
```

Do you want to reach out to the team about potentially fixing this for us?

in the meantime are you happy reviewing and merging the test on only 3.8 and 3.9 and adding 3.7 support back when this gets resolved?

**Comment by rpauly18** [comment]
@ssolson this looks good. Thanks for getting Github actions set up. We can merge this as is and I will see about getting the rex team to fix the issue with 3.7.

**Pull request merged**
