### PR TITLE
MHKiT v0.8.1

### PR DESCRIPTION
**Pull request by ssolson**
# MHKiT v0.8.1
MHKiT v0.8.1, includes bug fixes in the example notebooks and fixes the dependencies to requirements updates prior to Numpy 2.0.0.

Fixes MHKIT v0.8.0 installation issues (#334) by fixing the dependencies.
- https://github.com/MHKiT-Software/MHKiT-Python/pull/335

Fixes bugs in MHKiT example notebooks
- https://github.com/MHKiT-Software/MHKiT-Python/pull/327

### CODE REVIEW

**Comment by ssolson** [comment]
@akeeste are you around today to review this minor update?

**Comment by akeeste** [comment]
@ssolson yes I can review this morning. the changes are pretty straight forward since it's just 2 recent PRs. I will test a couple things locally and look into the failing test

**Comment by ssolson** [comment]
> @ssolson yes I can review this morning. the changes are pretty straight forward since it's just 2 recent PRs. I will test a couple things locally and look into the failing test

This looks like an Actions issue. I'm really hoping it just passes on a rerun. This just passed in the previous PR. We are also dropping 3.8 support soon, soo personally I'm less concerned with this test failing versus getting fresh installs of MHKiT to work for everyone ASAP.

**Comment by ssolson** [comment]
Actually you can see the test passed on PR but failed on push. I need to adjust the actions in the future so it only does PR or push not both to master

image

**Comment by akeeste** [comment]
> Actually you can see the test passed on PR but failed on push. I need to adjust the actions in the future so it only does PR or push not both to master
> 
> image

Good to know. I'm not too worried about the odd failing combination. The hindcast tests are really bogging us down... I'm looking into this today

**Comment by ssolson** [comment]
All tests passed on re-run.

**Pull request merged**
