### PR TITLE
Coords 

### PR DESCRIPTION
**Pull request by browniea**
Added file named for D3D `mapformat=4` 

Added function `_get_cords_to_layers`

### CODE REVIEW

**Comment by browniea** [comment]
Planning to reformate similar to [Wave moduel](https://github.com/MHKiT-Software/MHKiT-Python/blob/develop/mhkit/wave/io/ndbc.py) line 670

**Comment by ssolson** [comment]
Hey @browniea  apologies for messing this PR up. This should be easier going forward but there were some inconsistencies in how PR merged strategies were applied by the final merge author which made this messier. I perhaps should have just accepted the mess but instead decided to squash into master. My preferred strategy going forward is to squash PRs to develop and merge by ort into master.

To ensure master and develop are even I did a force rebase on origin develop.

That said can you either rebase or resubmit this PR? 
The official approach is to:
```
git checkout develop
git fetch origin
git reset --hard origin/develop

git checkout feature-branch
git rebase develop
git push user-fork feature-branch --force
```

That said rebasing may be extremely painful and it might be easier to just start from the new develop and remake the changes. Apologies for the trouble on this.

**Comment by ssolson** [comment]
Hey @browniea I was playing around with the D3D files today and what we want to determine the different key variables is the Conventions.

```
filename = "./tanana50_map.nc"
dflow_map = xr.open_dataset(filename)
dflow_map.Conventions
```
> 'UGRID-0.9'

A newer file I was working with from chris returns `'CF-1.8 UGRID-1.0 Deltares-0.10' 


Using this keyword should direct the variable names we use

**Comment by ssolson** [comment]
Closed due to inactivity

**Pull request closed without merging**
