### PR TITLE
Dolfyn cleaning function updates

### PR DESCRIPTION
**Pull request by jmcvey3**
Renames and makes the functions that calculate water depth and remove surface interference more robust. The functions were designed around Nortek ADCPs but didn't take into account the calculations RDI already does. Errors or warnings will guide the user through the proper use of functions if previous calculations were already completed or data is missing. 

Also removes the "ignore rankwarning" as some users may not want to do so, and updates future package deprecations.

Solves the problems Calum and I found in Issue #353. Tests were updated as appropriate.

Also added some fixes for determining beam angle and carrier frequency attributes for Sentinel V ADCPs.

### CODE REVIEW

**Comment by ssolson** [comment]
@jmcvey3 is this ready for review?

**Comment by jmcvey3** [comment]
> @jmcvey3 is this ready for review?

It is. I've also done some serious reorganizing of the I/O files in an attempt to make them easier to follow, and have added a few random fixes for random hiccups. The fix for 535 is in the first couple commits.

**Comment by ssolson** [comment]
Thanks James. I plan to tackle this Monday.

**Review by ssolson — COMMENTED** [review]
@jmcvey3 thanks for fixing the bug and improving the modularity of the dolfyn module.

I was adding docstrings to what I thought were new functions but realized they were primarily moved functions in our meeting yesterday. As such I will finish improving docstrings when we get to linting this module in the future. 

That said could you review the proposed docstrings I already did?

**Comment by jmcvey3** [comment]
> @jmcvey3 thanks for fixing the bug and improving the modularity of the dolfyn module.
> 
> I was adding docstrings to what I thought were new functions but realized they were primarily moved functions in our meeting yesterday. As such I will finish improving docstrings when we get to linting this module in the future.
> 
> That said could you review the proposed docstrings I already did?

Yep, and sounds like a plan

**Comment by jmcvey3** [comment]
@ssolson Did you want me to update certain files with docstrings and typehints in this PR, or shall we merge this one as is and do so in another?

**Comment by akeeste** [comment]
@ssolson looks like the ``typer`` [import](https://github.com/MHKiT-Software/MHKiT-Python/actions/runs/12036211804/job/33556913353?pr=354#step:6:37) is throwing an error as it is not an explicit dependency of mhkit. Should this package be included via one of our other dependencies or called out explicitly?

#360 will resolve the DeprecationWarnings

**Comment by ssolson** [comment]
> @ssolson looks like the `typer` [import](https://github.com/MHKiT-Software/MHKiT-Python/actions/runs/12036211804/job/33556913353?pr=354#step:6:37) is throwing an error as it is not an explicit dependency of mhkit. Should this package be included via one of our other dependencies or called out explicitly?
> 
> #360 will resolve the DeprecationWarnings

No it should be `typing` and in default python I pushed a fix.

**Pull request merged**
