### PR TITLE
In `wave.resource.surface_elevation` use `sum_of_sines` method if input spectrum does not have a zero frequency

### PR DESCRIPTION
**Pull request by simmsa**
Add `auto` method to wave.resource.surface_elevation to address #308. 

The `auto` method chooses the most computationally efficient surface
elevation computation method based on the input spectrum. `auto` uses
the `sum_of_sines` method is a zero frequency is not defined in the input spectrum
index and uses the `ifft` for all other cases.

### CODE REVIEW

**Comment by akeeste** [comment]
Thanks @simmsa. The other xarray PR is merged so we can address this quick before our release. I definitely like addressing the zero-frequency behavior in some way without an error. I think we should either:
- default to the ``auto`` method, but not throw a warning. I think an automatic method already implies we're choosing for the user, though the warning does indicate which method is ultimately chosen.
- or keep ``ifft`` as the default method, and revert to ``sum_of_sines`` with a warning if there is no zero frequency

 I'm leaning towards the latter since there are less options for the user to choose from. Thoughts?

**Comment by simmsa** [comment]
@akeeste, the latter is a great suggestion and simplifies the design. The latest changes remove `auto` and set `ifft` as the default method. If the method is `ifft` and the user inputs a spectrum with a zero frequency we warn the user and set the method to `sum_of_sines`.

**Review by akeeste — APPROVED** [review]
Thanks @simmsa! This PR looks good to me. I see it's still a draft. Are there any other additions here or are we good to merge?

**Comment by ssolson** [comment]
Please do not merge this until after #307.

**Comment by simmsa** [comment]
@ssolson, sorry for the poor timing of this PR. This does not need to be included in the latest release. Thank you!

**Comment by simmsa** [comment]
@akeeste this is good to go now! The test failure in MHKiT-MATLAB is unrelated to this change. #313 adds a fix for the `dim_0` error.

**Comment by ssolson** [comment]
Hey @simmsa apologies for messing this PR up. This should be easier going forward but there were some inconsistencies in how PR merged strategies were applied by the final merge author which made this messier. I perhaps should have just accepted the mess but instead decided to squash into master. My preferred strategy going forward is to squash PRs to develop and merge by ort into master.

To ensure master and develop are even I did a force rebase on origin develop.

That said can you either rebase or resubmit this PR? The official approach is to:
```
git checkout develop
git fetch origin
git reset --hard origin/develop

git checkout feature-branch
git rebase develop
git push user-fork feature-branch --force
```

That said rebasing may be extremely painful and it might be easier to just start from the new develop and remake the changes. Apologies for the trouble on this.

**Comment by ssolson** [comment]
@simmsa when you get a chance could you look to resolve the merge conflicts to we can close this PR?

**Pull request closed without merging**
