### PR TITLE
Update Nortek reader C types

### PR DESCRIPTION
**Pull request by jmcvey3**
Fix for below 0 water temperature

Pitch and roll should be able to go negative as well

### CODE REVIEW

**Comment by jmcvey3** [comment]
Issue #298

**Comment by jmcvey3** [comment]
@ssolson Found a datafile that has below 0 temps, though also found that pitch/roll/heading are inconsistent on whether they are signed

**Review by ssolson — APPROVED** [review]

**Comment by ssolson** [comment]
@jmcvey3 great work on turning this around so quickly!

**Comment by jmcvey3** [comment]
@ssolson No worries, glad it was an easy one!

**Pull request merged**
