### PR TITLE
Fix wave elevation function.

### LINKED ISSUE #140: wave elevation function is very slow
```python
elev = surface_elevation(S, time) 
```
is about 20 times slower than 

```python
elev = np.zeros(time.shape)
for ifreq, iS in S.T.iteritems(): 
    elev += iS[0] * np.cos(ifreq*2*np.pi * time + np.random.rand()*2*np.pi)
```

### LINKED ISSUE #142: Time array not used correctly in wave.resource.surface_elevation
Currently the different spectral arrays are being truncated using the start and  end time, e.g. 
```python
phase = phase[start_time:end_time]
```
but these Panda arrays are indexed by frequency (Hz) not time.   It is not doing what it is supposed to be doing.

### PR DESCRIPTION
**Pull request by cmichelenstrofer**
Fixes #140. Fixes #142.

### CODE REVIEW

**Comment by cmichelenstrofer** [comment]
@ssolson and Rebecca could you review this? 

- Bug fix: 
  - not truncating the spectrum anymore (was being truncated based on time value, but the `pd.Series` was indexed by frequency).
- Speedup 
  - moved calculation of `B` outside loop
   - replaced list comprehension + itertools with `np.outer` function
   - avoided creating a  complex array to then take the real part only, instead create the real part directly.
 - Functionality:
   - changed default seed to `None`. The default behavior should be creating a random phase. A  user can specify a  seed for reproducibility. Should not be the other way around (where we were hardcoding a phase as the default behavior). 
 - Tests:
   - There were two tests that did nothing. They would always pass. Their intention were to check that the default behavior and specifying the seed in the function signature gave the same results. But they always will even if the function is broken.  I commented these out but think they should be deleted. 
 - Examples:
   - I couldn't find an existing notebook that uses the `surface_elevation` function. If there isn't one, maybe we should add it to an existing example. 
 - Reference
   - We need to find a good reference for this function (converting frequency domain to time domain)

**Comment by rpauly18** [comment]
@cmichelenstrofer happy to review this. Are you still working on the fix for why the tests are failing, or would you like for me to look into this?

**Comment by cmichelenstrofer** [comment]
@rpauly18 I just fixed the tests. You can go ahead and review it. Thanks!

**Review by rpauly18 — APPROVED** [review]
Looks good. Are you still working on more changes, or is this ready to be converted from a draft?

**Comment by cmichelenstrofer** [comment]
@rpauly18 just changed it from '_draft_' to '_ready to review_'.  I deleted the two obsolete tests that I had commented out.

**Comment by cmichelenstrofer** [comment]
Something wrong with the tests. They were passing before and nothing changed other than deleting comments. Seems the issue is not with this PR but with accessing some data at NREL needed for the tests.

**Comment by rpauly18** [comment]
@cmichelenstrofer random failures happen sometimes because of the WPTO hindcast server being overloaded with request. I restarted the tests. If they fail again, I will investigate further.

**Comment by cmichelenstrofer** [comment]
@rpauly18 can this be merged?

**Pull request merged**
